version: "3.8"
services:
  drupaldb:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:8.0.34-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - ./:/docker-entrypoint-initdb.d

  phpmyadmin:
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    image: phpmyadmin/phpmyadmin
    ports:
      - "9082:80"
    restart: always
    environment:
      PMA_HOST: drupaldb
    depends_on:
      - drupaldb

  drupal:
    container_name: ${DRUPAL_CONTAINER_NAME}
    image: drupal:php8.2-fpm-bookworm
    ports:
      - 8082:80
    volumes:
      - ./web:/var/www/html
      - ./vendor:/opt/drupal/vendor
      - ./composer.json:/opt/drupal/composer.json
      - ./composer.lock:/opt/drupal/composer.lock
    depends_on:
      - drupaldb
